.TH prosopon 1  "May 2012" "version 0.1" "Prosopon"
.SH NAME
prosopon \- The Prosopon language interpreter

.SH SYNOPSIS
.B prosopon [-h | --help] [-yydebug] [-yy_flex_debug] [-v...] [-nostd] [-l LIBRARY]... [FILE...]

.SH DESCRIPTION


.SH OPTIONS
.TP
\-h, --help
Display brief help text and exits.
.TP
\-yydebug
Enable Bison debug output.
.TP
\-yy_flex_debug
Enable Flex debug output.
.TP
\-v...
Enable debug output and specify verbosity of output. 
.TP
\-nostd
Disable automatic loading of the Prosopon standard library.
.TP
\-l LIBRARY
Load a Prosopon standard library.

.SH AUTHOR
Matt Bierner (mattbierner (at) gmail.com)

.SH SEE ALSO
prosopon0.1(1)